server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima54
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
      host: 169.254.51.251
      username: /leyou
      password: leyou
      virtual-host: /leyou
  redis:
    host: 169.254.51.251
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    hostname: localhost
mybatis:
  type-aliases-package: com.leyou.user.pojo
logging:
  level:
    com.leyou: debug